version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11

    working_directory: ~/Garage-Helper

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Build server
          command: yarn run build:server:p

      - run:
          name: Build app bundle
          command: yarn run build:p

      - run:
          name: Build and push Docker image
          command: |
            cd production/server/
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t amarine7882/garage-helper:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push amarine7882/garage-helper:$TAG