version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:10.11

    working_directory: ~/Garage-Helper

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies{{ checksum "package.json" }}
            - dependencies

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Create config files
          command: |
            touch server/config
            echo "exports.MONGO_USER = undefined;" >> server/config
            echo "exports.MONGO_PASS = undefined;" >> server/config

      - run:
          name: Build bundles
          command: |
            yarn run build:server:p
            yarn run build:p

      - save_cache:
          key: bundle
          paths:
            - ~/Garage-Helper/production/app

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            cd production/server/
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t amarine7882/garage-helper:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push amarine7882/garage-helper:$TAG

  push-to-s3:
    docker:
      - image: circleci/python:2.7-jessie

    working_directory: ~/Garage-Helper

    steps:

      - restore_cache:
          key: bundle

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Deploy to S3
          command: aws s3 cp ~/Garage-Helper/production/app/bundle.js s3://garage-helper/app/ --content-type application/javascript --content-encoding gzip --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only: master

      - push-to-s3:
          requires:
            - build-test
          filters:
            branches:
              only: master