version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11

    working_directory: ~/Garage-Helper

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test

      - run:
        name: Build bundles
        command: |
          yarn run build:p
          yarn run build:server:p

      - run:
          name: Build and push Docker image
          command: |
            cd production/server/
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t amarine7882/garage-helper:$TAG
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push amarine7882/garage-helper:$TAG

  deploy:
    docker:
      - image: circleci/node:10.11
    working_directory: ~/Garage-Helper
    steps:

      - run:
        name: Install awscli
        command: sudo pip install awscli

      - run:
        name: Deploy to S3
        command: aws s3 cp ~/Garage-Helper/production/app/bundle.js s3://garage-helper/app/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master